---
title: "IFNg motifs"
author: "M.S. & co"
date: "18/5/2020"
output:
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(data.table)
library(stringr)
library(stringdist)
library(reshape2)
library(ggrepel)
library(cowplot)
library(igraph)
library(ggsci)
library(ggpubr)
library(ggplot2)
library(ggseqlogo)
library(msa)
library(Biostrings)
library(parallel)
select = dplyr::select
```

```{r}
# 1477 и 1465
list(
  fread("data/tcrnet.CD4_ifng.pool.strict.table.txt") %>%
    mutate(subset = "CD4ifng+"),
  fread("data/tcrnet.CD8_ifng.pool.strict.table.txt") %>%
    mutate(subset = "CD8ifng+")) %>%
  rbindlist() %>%
  group_by(subset) %>%
  mutate(p.value.adj = p.value.g %>% p.adjust,
         odds = log2((degree.s + 1) / (group.count.s + 1) / (degree.c + 1) * (group.count.c + 1))) %>%
  mutate(sel = degree.s > 1 & odds > 2 & p.value.adj < 0.05) -> data
```

```{r}
df.vdjdb <- fread("../tetramer/tetramer.txt") %>%
  mutate(species = "HomoSapiens") %>%
  select(cdr3, v.segm, j.segm, antigen.epitope, gene, species) %>%
  unique


compute_edges <- function(cdr3.1, cdr3.2) {
  stringdistmatrix(cdr3.1 %>% unique, cdr3.2 %>% unique, 
                   method = "hamming", 
                   nthread = 80,
                   useNames = "strings") %>%
    as.matrix %>%
    melt %>% 
    filter(value == 1) %>%
    mutate(cdr3.from = as.character(Var1), 
           cdr3.to = as.character(Var2)) %>%
    select(-Var1, -Var2, -value) %>%
    unique
}
compute_edges(data$cdr3aa %>% unique,
              df.vdjdb %>% filter(gene == "TRB") %>% .$cdr3 %>% unique) -> igtet.matches
colnames(igtet.matches) <- c("cdr3aa", "vdjdb.cdr3")

merge(data, igtet.matches) -> data.match.tet

data.match.tet %>%
  arrange(p.value.g)
```

```{r}
data %>%
  filter(sel) %>%
  group_by(subset) %>%
  summarize(count = n())

data %>%
  filter(p.value.adj < 1) %>%
  ggplot(aes(x = odds, y = -log10(p.value.adj + 1e-10))) +
  geom_point(aes(size = freq, color = !sel), alpha = 0.5) +
  geom_text_repel(data = data.match.tet %>% filter(sel), 
                  aes(label = vdjdb.cdr3), min.segment.length = 0, nudge_x = 5) +
  scale_color_npg(name="TCRNET core?", labels = c("Y", "N")) + 
  #scale_color_distiller(palette = "Blues", direction = 1) +
  scale_size("Frequency") +
  ylab("-log10 Padj") +
  scale_x_continuous("log2 Enrichment odds ", limits = c(0,15)) +
  theme_pubr() +
  facet_wrap(~subset) +
  theme(legend.position = "bottom") -> p_enrich

p_enrich

pdf("figX2a.pdf", width = 6, height = 4)
p_enrich
dev.off()
```

```{r}
# I - between enriched and neighbors
data.e <- data %>%
  #group_by(subset) %>%
  do(compute_edges(.$cdr3aa[which(.$sel)], 
                   .$cdr3aa)) %>%
  ungroup

compute_cc <- function(from, to) {
  set.seed(42)
  gg <- data.frame(from, to) %>%
    graph_from_data_frame %>%
    simplify
  
  cc <- gg %>%
    clusters
  
  coords <- gg %>%
      layout_with_graphopt(niter = 3000, charge = 0.01)
  
  data.frame(cdr3aa = names(V(gg)),
             x = coords[,1],
             y = coords[,2],
             stringsAsFactors = F) %>%
    merge(data.frame(cdr3aa = names(cc$membership),
                 cid.0 = cc$membership,
                 stringsAsFactors = F))
}

data.cc <- data.e %>%
  group_by(subset) %>%
  do(compute_cc(.$cdr3.from, .$cdr3.to)) %>%
  merge(data %>% select(cdr3aa, subset) %>% unique) %>%
  ungroup %>%
  mutate(cid = paste(subset,
                     cid.0, sep = ".")) %>%
  group_by(cid) %>%
  mutate(csz = n()) %>%
  ungroup
```

```{r}
data.cc %>%
  group_by(subset) %>%
  summarize(len = mean(nchar(cdr3aa)))

data.cc %>%
  filter(csz > 3) %>%
  ggplot(aes(x = x, y = y))+#log10(csz / total))) +
  geom_point(color = "black", size = 2) +
  #geom_density_2d(h=c(100, 100), aes(group = cid.0), color = "grey30") +
  geom_point(aes(color = nchar(cdr3aa))) +
  xlab("") + ylab("") +
  scale_color_distiller("CDR3 len.", palette = "Spectral",
                       direction = 1, breaks = c(10,12,14,16,18,20)) +
  facet_wrap(~ subset, scales = "free") +
  theme_pubr() +
  theme(aspect = 1,
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        legend.position = "bottom") -> p_clusters

p_clusters

pdf("figX2b.pdf", width = 6, height = 7)
p_clusters
dev.off()

data.cc %>%
  merge(data %>% group_by(subset, cdr3aa) %>% summarize(freq = sum(freq))) %>%
  group_by(cid.0, subset) %>%
  summarize(csz = csz[1], freq = sum(freq)) %>%
  group_by(subset) %>%
  summarize(cuniq = length(unique(cid.0)),
            csz.m = mean(csz),
            freq = mean(freq) * 100)
```

```{r}
data.raw <- data.frame(filename = list.files("data/"), stringsAsFactors = F) %>%
  filter(startsWith(filename, "nc")) %>%
  mutate(sample = gsub("nc\\.vdj\\.", "", filename)) %>%
  mutate(sample = gsub("_beta\\.clonotypes\\.TRB\\.txt", "", sample)) %>%
  mutate(sample = gsub("Project__", "", sample)) %>%
  mutate(sample = gsub("ifny", "ifng+", sample)) %>%
  mutate(donor = gsub(".+_p", "p", sample)) %>%
  mutate(sample.subset = str_split_fixed(donor, "_", 3)[,2],
         donor = str_split_fixed(donor, "_", 3)[,1]) %>%
  group_by(filename, sample, sample.subset, donor) %>%
  do(fread(paste0("data/", .$filename[1])))
```

```{r}
data.raw.cc <- data.raw %>%
  merge(data.cc %>% select(cdr3aa, subset, x, y, cid, cid.0, csz))

data.raw.cc %>%
  filter(csz > 2) %>%
  ggplot(aes(x = x, y = y, size = freq,
             color = sample.subset)) +
  geom_point() +
  facet_wrap( ~ donor, nrow = 2) +
  scale_color_npg(name = "Subset") +
  scale_size("Frequency") +
  xlab("") + ylab("") +
  theme_pubr() +
  theme(aspect = 1,
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        legend.position = "right") -> p_clusters2
p_clusters2

pdf("figX2c.pdf", width = 10, height = 6)
p_clusters2
dev.off()
```

```{r}
data.raw.cc %>%
  filter(cdr3aa == "CASSDSDTGELFF") %>%
  .$cid.0 %>%
  unique -> cid.0.tet

data.raw.cc %>%
  filter(substr(cid, 1, 3) == substr(sample.subset, 1, 3)) %>%
  group_by(cid.0, sample.subset, donor) %>%
  summarise(freq = sum(freq)) %>%
  group_by(sample.subset, cid.0) %>%
  mutate(publicity = length(unique(donor)), 
         public = publicity > 1) -> data.raw.cc.s

data.raw.cc.s %>%
  group_by(sample.subset, publicity) %>%
  summarize(count = length(unique(cid.0))) %>%
  group_by(sample.subset) %>%
  mutate(freq = count / sum(count)) %>%
  ungroup %>%
  group_by(sample.subset) %>%
  arrange(desc(publicity)) %>%
  mutate(ypos = cumsum(freq) - 0.5*freq ) %>%
  ungroup -> data.raw.cc.s2

data.raw.cc.s2

data.raw.cc.s2 %>%
  ggplot(aes(x = 0, y = freq)) +
  geom_bar(data = data.frame(freq = 1), 
           stat="identity", position = "stack",
           color = "black", fill = "black") +
  geom_bar(stat="identity", position = "stack",
           aes(fill = publicity %>% as.factor), color = NA) +
  coord_polar("y", start = 0) +
  facet_wrap(~sample.subset) + xlab("") + ylab("") +
  geom_text_repel(aes(y = ypos, x= 0.4, label = count), color = "black",
                  nudge_x = 0.2) +
  scale_fill_brewer("Publicity", palette = "YlOrRd") +
  theme_pubclean() +
  theme(aspect = 1,
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        legend.position = "bottom") -> p_publ_s
p_publ_s

pdf("figX2d.pdf", width = 6, height = 6)
p_publ_s
dev.off()

data.raw.cc.s %>%
  filter(sample.subset != "PBMC") %>%
  filter(publicity > 1) %>%
  ggplot(aes(y = donor,
             x = paste0("C", cid.0))) +
  geom_point(data = data.frame(donor = unique(data.raw.cc.s$donor),
                               cid.0 = unique(cid.0.tet),
                               freq = 0.0,
                               sample.subset = "CD8ifng+"),
             shape = 15, color = "grey",
             size = 10) +
  geom_point(shape = 21, aes(fill = publicity,
                             size = freq),
             color = "grey30") +
  facet_wrap( ~ sample.subset, scales = "free_x") +
  scale_size_continuous(name = "Frequency" ) +
  scale_fill_distiller(guide = F, name = "Frequency",
                       palette = "YlOrRd", direction = 1,
                       limits = c(1,5)) +
  xlab("TCR cluster ID") + ylab("") +
  theme_pubr() +
  theme(aspect = 1,
        legend.position = "top",
        panel.grid.major = element_line(linetype = "dashed", colour = "grey30",size=0.1),
        axis.text.x = element_text(angle = 90, hjust = 1, vjust= 0.5)) -> p_publ
p_publ

pdf("figX2e.pdf", width = 6, height = 6)
p_publ
dev.off()
```

```{r}
data.raw.cc %>%
  filter(sample.subset == "CD8ifng+",
         subset == "CD8ifng+",
         cid.0 == cid.0.tet) %>%
  group_by(cdr3aa) %>%
  summarize(freq = mean(freq), 
            sample.subset = paste0(sample.subset %>% sort %>% unique, collapse = ","),
            n.donor = length(unique(donor)),
            donor = paste0(donor %>% sort %>% unique, collapse = ","))

data.raw.cc %>%
  ungroup %>%
  filter(sample.subset %in% c("CD8ifng+", "PBMC"),
         subset == "CD8ifng+",
         cid.0 == cid.0.tet) %>%
  group_by(sample.subset, cdr3aa) %>%
  summarize(freq = mean(freq), 
            #sample.subset = paste0(sample.subset %>% sort %>% unique, collapse = ","),
            n.donor = length(unique(donor)),
            donor = paste0(donor %>% sort %>% unique, collapse = ",")) -> data.C2.tet
```

```{r}
data.raw.cc %>%
  filter(sample.subset == "PBMC", 
         subset == "CD8ifng+",
         cid.0 == cid.0.tet) %>% unique -> data.C2.tet.2
C2.seqs <- data.C2.tet.2$cdr3aa
names(C2.seqs) <- paste(gsub("LTI", "", data.C2.tet.2$donor), 
                        gsub("TRB", "", data.C2.tet.2$v), 
                        gsub("TRB", "", data.C2.tet.2$j))

AAStringSet(C2.seqs) %>%
  msa() %>% msaPrettyPrint(askForOverwrite = F, file = "C2_motif.pdf",
                           psFonts=T,
                           showLegend=FALSE, showNumbering = "none", 
                           showNames = "left", shadingMode = "functional", 
                           shadingModeArg = c("hydropathy"),
                           logoColors = "hydropathy")
```

```{r}
data.raw.cc %>%
  select(-filename) %>%
  fwrite("all_data_clusters.txt", sep = "\t")
```

```{r}
```
